services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3605:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links: 
      - postgres
  postgres:
    image: postgres:latest
    container_name: desafio3all
    restart: always
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "3604:5460"
    
#docker compose up -d  docker compose stop e docker compose down